# Generated by Django 4.0.2 on 2022-08-30 16:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ferramenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('resumo', models.TextField()),
                ('data_criacao', models.DateField(default=datetime.datetime.today)),
                ('link', models.URLField()),
            ],
        ),
    ]
