# Generated by Django 4.0.2 on 2022-07-22 21:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tutorial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('titulo_para_url', models.CharField(max_length=100)),
                ('capa', models.ImageField(upload_to='tutoriais/%Y/%m/%d/')),
                ('data_publicacao', models.DateField(default=datetime.datetime.today)),
                ('tempo_de_leitura', models.IntegerField()),
                ('tempo_de_video', models.IntegerField(blank=True)),
                ('motivacao', models.TextField()),
                ('url_video', models.URLField(blank=True)),
                ('conteudo', models.TextField()),
                ('resumo', models.TextField()),
                ('publicado', models.BooleanField(default=False)),
            ],
        ),
    ]
