# Generated by Django 4.0.2 on 2022-07-22 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutoriais_cyber_sec', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='Tutorial',
            name='categoria',
            field=models.TextField(choices=[('Celulares', 'Celulares'), ('Computadores', 'Computadores'), ('Navegadores', 'Navegadores'), ('Redes Sociais', 'Redes Sociais')], default='', max_length=20),
            preserve_default=False,
        ),
    ]
