# Generated by Django 4.0.2 on 2022-06-01 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_cyber_sec', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='artigo',
            name='referencias',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
