# Generated by Django 4.0.2 on 2022-06-25 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artigos_cyber_sec', '0003_artigo_resumo'),
    ]

    operations = [
        migrations.AddField(
            model_name='artigo',
            name='tema',
            field=models.TextField(choices=[('Seguranca Cibernetica', 'Ciberseg'), ('Seguranca Cibernetica | Crimes Cibernéticos', 'Ciberseg Crimes'), ('Seguranca Cibernetica | LGPD', 'Ciberseg Lgpd')], default='', max_length=45),
            preserve_default=False,
        ),
    ]
