# Generated by Django 4.0.2 on 2022-07-22 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artigos_cyber_sec', '0004_artigo_tema'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artigo',
            name='titulo_para_caminho',
        ),
        migrations.AddField(
            model_name='artigo',
            name='titulo_para_url',
            field=models.CharField(default='', max_length=45),
            preserve_default=False,
        ),
    ]
